# Generated by Django 4.1.4 on 2023-07-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_item', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('describe', models.CharField(max_length=255)),
            ],
        ),
    ]
